name: tests

on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y lua5.3

      - name: Run tests
        run: lua tests/all.lua
